### ISSUE TITLE
Missing parameter in authFinish::handleAccessTokenResponse

### ISSUE THREAD

**Issue by mrdjohnson** [stevenroose/dart-reddit#10]
NoSuchMethodError: No top-level method 'handleAccessTokenResponse' with matching arguments declared.
Receiver: top-level
Tried calling: handleAccessTokenResponse(Instance of 'Response', Instance of '_SimpleUri', Instance of 'DateTime', Instance(length:1) of '_GrowableList')
Found: handleAccessTokenResponse(Response, Uri, DateTime, List<String>, String)

This happened for me on line 147:

      `oauth2.Credentials credentials = handleAccessTokenResponse(response, _TOKEN_ENDPOINT, startTime, ["*"];`

fixed by adding empty quotes in the parameter list (not sure what the actual value is supposed to be though)

**Comment by stevenroose** [comment]
Are you talking about [this line](https://github.com/stevenroose/dart-reddit/blob/master/lib/src/reddit.dart#L160)? It does have the quotes there..

**Comment by mrdjohnson** [comment]
Strange. The line is missing when I pulled it down from the pub

**Comment by stevenroose** [comment]
Oh, perhaps it's not been updated on pub, let me check that!

**Comment by stevenroose** [comment]
I pushed an update to pub. I'm very sorry for the inconvenience!

**Comment by mrdjohnson** [comment]
Thanks for the fix! Glad I could "help"
