### ISSUE TITLE
Strong mode support?

### ISSUE THREAD

**Issue by refi64** [stevenroose/dart-reddit#8]
Strong mode is going to be the default in Dart 2.0 (and is already the default for Flutter apps and required for DDC apps), and JsonObject flat-out doesn't seem to work with it. I made [a fork](https://github.com/kirbyfan64/dart-reddit/commit/574111b96deff1a622af354cea8dd11e666bea75), but it was a hack I threw together in ~5 minutes, and the API is now really ugly because I can't use dot syntax...

I think the best way would be to just manually deserialize the API results into actual Dart classes?

**Comment by stevenroose** [comment]
Haven't done any Dart in some time. Could you point me to a document
describing strong mode requirements?

Does it mean we can't use JSON as maps anymore? I'm on my phone, will try
to take a look at your fork this week!

**Comment by refi64** [comment]
@stevenroose It just means you can't do stuff like `myobject.xyz` on a `JsonObject`; it needs to be `myobject['xyz']`.

I can try working on this too if you prefer.

**Comment by stevenroose** [comment]
So there is no `noSuchMethod`?

**Comment by stevenroose** [comment]
@kirbyfan64  Does this PR solve the strong mode problem? https://github.com/stevenroose/dart-reddit/pull/9

**Comment by stevenroose** [comment]
Fixed in https://github.com/stevenroose/dart-reddit/pull/9.
